spring.application.name=jobportal

# Enable DevTools live reload and restart
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

spring.profiles.active=${ENV:dev}
